"""seeder-skills

Revision ID: 2f7f97a39483
Revises: 52f2bd6a4479
Create Date: 2024-02-14 01:12:45.597406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session


# revision identifiers, used by Alembic.
revision: str = '2f7f97a39483'
down_revision: Union[str, None] = '52f2bd6a4479'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = Session(bind=bind, autocommit=False, autoflush=True)

    # Call the seed function
    from seeder.skills import seed_skills
    seed_skills(session)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
