"""updated-models

Revision ID: 52f2bd6a4479
Revises: f5f9278f9f95
Create Date: 2024-02-14 00:47:32.770169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52f2bd6a4479'
down_revision: Union[str, None] = 'f5f9278f9f95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_experiences', 'company',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('job_experiences', 'location',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.add_column('profile_skills', sa.Column('profile_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'profile_skills', 'profiles', ['profile_id'], ['id'])
    op.create_foreign_key(None, 'profile_skills', 'skills', ['skill_id'], ['id'])
    op.drop_column('profile_skills', 'user_id')
    op.create_unique_constraint(None, 'profiles', ['user_id'])
    op.add_column('project_skills', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'project_skills', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(None, 'project_skills', 'skills', ['skill_id'], ['id'])
    op.drop_column('project_skills', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_skills', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'project_skills', type_='foreignkey')
    op.drop_constraint(None, 'project_skills', type_='foreignkey')
    op.drop_column('project_skills', 'project_id')
    op.drop_constraint(None, 'profiles', type_='unique')
    op.add_column('profile_skills', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'profile_skills', type_='foreignkey')
    op.drop_constraint(None, 'profile_skills', type_='foreignkey')
    op.drop_column('profile_skills', 'profile_id')
    op.alter_column('job_experiences', 'location',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('job_experiences', 'company',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
