"""country-seeder

Revision ID: f5f9278f9f95
Revises: 857c258f4107
Create Date: 2024-02-14 00:34:07.385035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session


# revision identifiers, used by Alembic.
revision: str = 'f5f9278f9f95'
down_revision: Union[str, None] = '857c258f4107'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = Session(bind=bind, autocommit=False, autoflush=True)

    # Call the seed function
    from seeder.country import seed_countries
    seed_countries(session)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
